import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Header } from '@/components/ui/header';
import { cn } from '@/lib/utils';
import './globals.css';
import { Banner } from '@/components/ui/banner';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi">
      <body className={cn('text-base antialiased', inter.className)}>
        <Header />
        <Banner />
        {children}
      </body>
    </html>
  );
}
